(()=>{'use strict';
const data=globalThis.BX2_DATA,app=document.querySelector('#app'),KEY='bx2-save',RECORD='bx2-record';
let lang=localStorage.getItem('bx2-lang')==='en'?1:0,screen='modes',state=null,message='';
const tr=(pl,en)=>lang?en:pl, name=x=>x.name[lang], esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const mode=id=>data.modes.find(x=>x.id===id),good=id=>data.goods.find(x=>x.id===id);
const goods=()=>data.goods.filter(x=>mode(state.mode).goods.includes(x.id)&&x.unlock<=state.day);
const price=id=>{const g=good(id),city=data.cities.find(x=>x.id===state.city);return Math.max(1,Math.round(g.base*city.factor*state.market*(((state.seed+state.day*17+g.base*13)%9+6)/10)))};
const worth=()=>state.cash+Object.entries(state.cargo).reduce((sum,[id,n])=>sum+n*price(id),0);
const fresh=id=>({schema:1,mode:id,day:1,cash:mode(id).cash,city:data.cities[0].id,market:1,cargo:{},seed:Math.floor(Math.random()*1000000),trades:0,finished:false});
const valid=s=>s&&s.schema===1&&s.mode==='child'&&Number.isInteger(s.day)&&s.day>=1&&s.day<=8&&Number.isSafeInteger(s.cash)&&s.cash>=0&&data.cities.some(x=>x.id===s.city)&&Number.isFinite(s.market)&&s.market>0&&s.market<2&&s.cargo&&typeof s.cargo==='object'&&Object.entries(s.cargo).every(([id,n])=>good(id)&&Number.isSafeInteger(n)&&n>=0)&&Number.isSafeInteger(s.seed)&&Number.isSafeInteger(s.trades)&&typeof s.finished==='boolean';
try{const saved=JSON.parse(localStorage.getItem(KEY));if(valid(saved))state=saved}catch{}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{message=tr('Nie udało się zapisać gry.','Could not save the game.')}}
function record(){const n=Number(localStorage.getItem(RECORD));return Number.isSafeInteger(n)&&n>=0?n:0}
function button(label,action,extra=''){return `<button type="button" data-action="${action}" ${extra}>${esc(label)}</button>`}
function renderModes(){app.innerHTML=`<section class="panel"><h1>${tr('Wybierz tryb','Choose a mode')}</h1><p>${tr('Wybierz rodzaj gry. Nie pytamy o wiek ani datę urodzenia.','Choose a game type. We do not ask for age or date of birth.')}</p><div class="mode-grid">${data.modes.map(m=>`<article class="mode-card"><h2>${esc(name(m))}</h2><p>${m.available?tr('7 dni handlu · cel 1300 monet · bez długu','7 trading days · goal 1300 coins · no debt'):tr('Wkrótce','Coming soon')}</p>${button(m.available?tr('Graj','Play'):tr('Wkrótce','Coming soon'),'start:'+m.id,m.available?'':'disabled')}</article>`).join('')}</div>${state&&!state.finished?button(tr('Kontynuuj','Continue'),'continue'):''}</section>`}
function renderGame(){const m=mode(state.mode),total=worth();if(state.finished){app.innerHTML=`<section class="panel"><h1>${tr('Koniec rundy','Round complete')}</h1><p>${tr('Wynik','Score')}: <strong>${total}</strong> · ${tr('Cel','Goal')}: ${m.goal}</p><p>${total>=m.goal?tr('Cel osiągnięty!','Goal reached!'):tr('Spróbuj ponownie.','Try again.')}</p><p>${tr('Rekord lokalny','Local best')}: ${record()}</p><p>${state.trades>=4?tr('Odznaka: Wytrwały handlarz','Badge: Persistent trader'):tr('Wykonaj 4 transakcje, by zdobyć odznakę.','Make 4 trades to earn a badge.')}</p>${button(tr('Nowa runda','New round'),'start:child')} ${button(tr('Tryby','Modes'),'modes')}</section>`;return}
const rows=goods().map(g=>`<tr><th scope="row">${esc(name(g))}</th><td>${price(g.id)}</td><td>${state.cargo[g.id]||0}</td><td><label class="sr-only" for="qty-${g.id}">${tr('Ilość','Quantity')}: ${esc(name(g))}</label><input id="qty-${g.id}" type="number" inputmode="numeric" min="1" max="9999" step="1" value="1"></td><td>${button(tr('Kup','Buy'),'buy:'+g.id)} ${button(tr('Sprzedaj','Sell'),'sell:'+g.id)}</td></tr>`).join('');
app.innerHTML=`<section class="panel"><div class="status"><h1>${tr('Dzień','Day')} ${state.day}/${m.days}</h1><p>${tr('Miasto','City')}: ${esc(name(data.cities.find(c=>c.id===state.city)))} · ${tr('Gotówka','Cash')}: ${state.cash} · ${tr('Majątek','Assets')}: ${total} / ${m.goal}</p></div><p>${tr('Kupuj tanio, sprzedawaj drożej. Podróż kończy dzień i zmienia ceny.','Buy low, sell high. Travel ends the day and changes prices.')}</p><div class="table-wrap"><table><thead><tr><th>${tr('Towar','Good')}</th><th>${tr('Cena','Price')}</th><th>${tr('Masz','Owned')}</th><th>${tr('Ilość','Quantity')}</th><th>${tr('Handel','Trade')}</th></tr></thead><tbody>${rows}</tbody></table></div><p class="notice" role="status">${esc(message)}</p><div class="actions"><label for="destination">${tr('Dokąd jedziesz?','Destination')}</label><select id="destination">${data.cities.filter(c=>c.id!==state.city).map(c=>`<option value="${c.id}">${esc(name(c))}</option>`).join('')}</select>${button(tr('Jedź — następny dzień','Travel — next day'),'travel')} ${button(tr('Tryby','Modes'),'modes')}</div><p class="hint">${tr('Nowe towary pojawią się w dniach 3–5. Skróty: Alt+T podróż, Alt+M tryby.','New goods appear on days 3–5. Shortcuts: Alt+T travel, Alt+M modes.')}</p></section>`}
function render(){document.documentElement.lang=lang?'en':'pl';document.querySelector('#language').textContent=lang?'PL':'EN';document.querySelector('#privacy-link').textContent=tr('Prywatność','Privacy');document.querySelector('#contrast').textContent=tr('Wysoki kontrast','High contrast');document.querySelector('#contrast').setAttribute('aria-pressed',String(document.body.classList.contains('high-contrast')));screen==='modes'?renderModes():renderGame();const s=data.sponsors.find(x=>x.approvedForChild);document.querySelector('#sponsor').innerHTML=s?`${tr('Partner projektu:','Project partner:')} <span class="sponsor-mark">${esc(s.logoText)}</span>`:'';document.querySelector('#offline').textContent=globalThis.BiznesPWA?.status(lang?'en':'pl')||tr('Gra lokalna','Local game')}
function trade(kind,id){if(!goods().some(g=>g.id===id))return;const n=Number(document.querySelector(`#qty-${id}`)?.value);if(!Number.isSafeInteger(n)||n<1||n>9999){message=tr('Wpisz poprawną ilość.','Enter a valid quantity.');renderGame();return}const cost=price(id)*n,owned=state.cargo[id]||0;if(kind==='buy'&&cost>state.cash){message=tr('Za mało gotówki.','Not enough cash.');renderGame();return}if(kind==='sell'&&n>owned){message=tr('Za mało towaru.','Not enough goods.');renderGame();return}state.cash+=kind==='buy'?-cost:cost;state.cargo[id]=owned+(kind==='buy'?n:-n);state.trades++;message=kind==='buy'?tr('Kupiono.','Bought.'):tr('Sprzedano.','Sold.');save();renderGame()}
function travel(){if(screen!=='game'||state.finished)return;const destination=document.querySelector('#destination').value;if(!data.cities.some(c=>c.id===destination&&c.id!==state.city))return;state.city=destination;state.day++;const event=data.events[(state.seed+state.day)%data.events.length];state.market=event.factor;message=name(event);if(state.day>mode(state.mode).days){state.finished=true;const score=worth();if(score>record())try{localStorage.setItem(RECORD,String(score))}catch{}}save();renderGame()}
app.addEventListener('click',e=>{const action=e.target.closest('[data-action]')?.dataset.action;if(!action)return;if(action.startsWith('start:')){const m=mode(action.slice(6));if(!m?.available)return;state=fresh(m.id);screen='game';message='';save();render();return}if(action==='continue'&&state){screen='game';render();return}if(action==='modes'){screen='modes';render();return}if(action==='travel'){travel();return}const [verb,id]=action.split(':');if(screen==='game'&&!state.finished&&(verb==='buy'||verb==='sell'))trade(verb,id)});
document.querySelector('#language').addEventListener('click',()=>{lang=1-lang;localStorage.setItem('bx2-lang',lang?'en':'pl');render()});document.querySelector('#contrast').addEventListener('click',()=>{document.body.classList.toggle('high-contrast');localStorage.setItem('bx2-contrast',document.body.classList.contains('high-contrast')?'1':'0');render()});document.addEventListener('keydown',e=>{if(!e.altKey)return;const key=e.key.toLowerCase();if(key==='m'){e.preventDefault();screen='modes';render()}else if(key==='t'&&screen==='game'&&!state.finished){e.preventDefault();travel()}});if(localStorage.getItem('bx2-contrast')==='1')document.body.classList.add('high-contrast');render();
})();
